---

- name: Install nginx magento1 vhosts
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0664
  notify: restart nginx
  with_items:
     - { src: magento1-vhost.conf.j2, dest: /etc/nginx/sites-available/www.conf }
     - { src: magento1-snippet.conf.j2, dest: /etc/nginx/snippets/magento.conf }
  tags:
    - nginx
  when: magento_version == "1"

- name: Install nginx magento2 vhosts
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0664
  notify: restart nginx
  with_items:
     - { src: magento2-vhost.conf.j2, dest: /etc/nginx/sites-available/www.conf }
  tags:
    - nginx
  when: magento_version == "2"
