---

- name: Ensure snippet files exist
  become: yes
  file:
    path: "/etc/nginx/snippets/{{ item }}"
    mode: 0664
    state: touch
  loop: "{{ nginx_snippet_includes }}"
  changed_when: false
  tags:
    - nginx
    - nginx-configure

- include_tasks: magento1.yml
  when: magento_version == "1"
  tags:
    - nginx
    - nginx-configure

- include_tasks: magento2.yml
  when: magento_version == "2"
  tags:
    - nginx
    - nginx-configure